// Generated by https://quicktype.io

export interface Transaction {
      path: string[];
      _id: string;
      name: string;
      required: boolean;
      disabled: boolean;
      display: boolean;
      type: string;
      displayText: string;
      defaultValue: string;
      __v: number;
    }
    